---
- hosts: all
  vars_files:
    - var.yaml
  tasks:
  - name: Add group "writer" to remote node
    group:
      name: devops
      gid: 2210
      state: present
  
  - name: Give sudo access
    blockinfile:
      path: /etc/sudoers
      insertafter: 'root    ALL=(ALL)       ALL'
      block: |
        # Gives sudo access to the devops group
        %devops        ALL=(ALL)       NOPASSWD: ALL

  - name: Add the user 'test'
    ansible.builtin.user:
      name: "{{ item.name }}"
      shell: /bin/bash
      uid: "{{ item.uid }}"
      groups: devops
      append: yes
    with_items: "{{ usernames_writer }}"

  - name: Deploy SSH Public Key
    ansible.posix.authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ item.key }}"
      state: present
    with_items: "{{ usernames_writer }}"



## Read User

  - name: Add group "reader" to remote node
    group:
      name: dev
      gid: 2211
      state: present


  - name: Add the user 'test'
    ansible.builtin.user:
      name: "{{ item.name }}"
      shell: /bin/bash
      uid: "{{ item.uid }}"
      groups: dev
      append: yes
    with_items: "{{ usernames_reader }}"

  - name: Deploy SSH Public Key
    ansible.posix.authorized_key:
      user: "{{ item.name }}"
      state: present
      key: '{{ item.key }}'
      state: present
    with_items: "{{ usernames_reader }}"



















# ---
# - hosts: all
#   vars:
#     username: test
#     userpass: user_password
#     pubkey: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
#   tasks:
#   - name: Add group "writer" to remote node
#     group:
#       name: devops
#       gid: 2212
#       state: present
  
#   - name: Add the user 'test'
#     ansible.builtin.user:
#       name: "{{ username }}"
#       shell: /bin/bash
#       password: "{{ userpass | password_hash('sha512') }}"
#       groups: devops
#       append: yes

#   - name: ll
#     command : ls /home/test/.ssh/id_rsa.pub

#   - name: Deploy SSH Public Key
#     ansible.posix.authorized_key:
#       user: "{{ username }}"
#       state: present
#       key: '{{ pubkey }}'
#       state: present